import React,{useEffect,useState} from 'react';
import {Users,BookOpen,ClipboardCheck,AlertTriangle,CheckCircle2,BrainCircuit,ArrowUpRight,Play,Loader2} from 'lucide-react';
import {Link} from 'react-router-dom';
import {Card,PageTitle,Stat,Badge,Progress, AiPill,SectionHeader} from '../components/UI';
import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
import {apiRequest} from '../api';

export default function Dashboard(){
 const [data,setData]=useState({faculty:0,courses:0,requests:0,pendingReview:0,workload:[],pending:[]});
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[agentBusy,setAgentBusy]=useState(false),[agentMessage,setAgentMessage]=useState('');
 const load=async()=>{try{setLoading(true);const r=await apiRequest({method:'GET',url:'/allocations/dashboard'});setData(r.data)}catch(e){setError(e?.response?.data?.message||'Backend unavailable. Start the server and refresh.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const runAgent=async()=>{try{setAgentBusy(true);setAgentMessage('');const r=await apiRequest({method:'POST',url:'/agent/run-allocation',data:{}});setAgentMessage(`AI allocation completed: ${r.data.approved||0} auto-approved, ${r.data.escalated||0} sent to HOD review.`);await load()}catch(e){setAgentMessage(e?.response?.data?.message||'AI allocation could not be completed.')}finally{setAgentBusy(false)}};
 const workload=data.workload||[];
 return <div className="grid-bg -m-4 sm:-m-7 p-4 sm:p-7 min-h-[calc(100vh-64px)]">
  <PageTitle eyebrow="HOD COMMAND CENTER" title="Faculty Course Allocation" desc="Manage faculty, courses, requests and AI-driven allocation recommendations from one workspace." action={<div className="flex flex-wrap gap-2"><button type="button" disabled={agentBusy} onClick={runAgent} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-[#0f766e] text-white text-sm font-semibold shadow-lg hover:bg-teal-700 disabled:opacity-50">{agentBusy?<Loader2 size={16} className="animate-spin"/>:<Play size={16}/>} {agentBusy?'Running AI allocation':'Run AI allocation'}</button><Link to="/review" className="inline-flex items-center px-4 py-2.5 rounded-xl bg-[#1d4ed8] text-white text-sm font-semibold shadow-lg hover:bg-blue-700">HOD review</Link></div>}/>
  {error&&<div className="mb-4 p-3 rounded-xl bg-red-50 border border-red-200 text-red-700 text-sm">{error}</div>}
  {agentMessage&&<div className="mb-4 p-3 rounded-xl bg-teal-50 border border-teal-200 text-teal-800 text-sm">{agentMessage}</div>}
  <div className="grid grid-cols-2 xl:grid-cols-4 gap-4">
   <Link to="/faculty" className="block text-left"><Stat label="Total faculty" value={loading?'…':data.faculty} sub="Manage faculty" icon={Users}/></Link>
   <Link to="/courses" className="block text-left"><Stat label="Courses" value={loading?'…':data.courses} sub="Manage courses & sections" icon={BookOpen}/></Link>
   <Link to="/requests" className="block text-left"><Stat label="Requests" value={loading?'…':data.requests} sub="View faculty requests" icon={ClipboardCheck}/></Link>
   <Link to="/review" className="block text-left"><Stat label="Pending review" value={loading?'…':data.pendingReview} sub="Requires HOD action" icon={AlertTriangle} tone="amber"/></Link>
  </div>
  <div className="grid xl:grid-cols-3 gap-5 mt-5">
   <Card className="xl:col-span-2 p-5"><div className="flex items-center justify-between mb-4"><h2 className="font-bold text-[#0b1f44]">Workload distribution</h2><Link to="/faculty" className="text-xs font-semibold text-blue-600 flex items-center gap-1 hover:text-blue-800">View all faculty</Link></div><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={workload} margin={{left:-18,right:8,top:8,bottom:0}}><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip/><Bar dataKey="hours" radius={[5,5,0,0]} fill="#2563eb"/></BarChart></ResponsiveContainer></div><div className="flex gap-5 text-xs text-slate-500"><span>Target max: 18 hrs</span><span>Live dataset data</span></div></Card>
   <Card className="p-5"><SectionHeader title="AI allocation status"/><p className="text-xs text-slate-500 -mt-2 mb-4">The agent processes the request set using verified faculty, course and workload data. Only ambiguous cases are sent to the HOD.</p><div className="rounded-2xl bg-blue-50 border border-blue-100 p-4"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-white text-blue-600 flex items-center justify-center"><BrainCircuit size={20}/></div><div><div className="font-bold text-sm">Agent ready</div><div className="text-xs text-slate-500 mt-1">{data.requests} requests available</div></div></div><div className="mt-4 grid grid-cols-2 gap-2"><div className="bg-white rounded-xl p-3"><div className="text-[11px] text-slate-500">Pending HOD</div><b className="text-lg">{data.pendingReview}</b></div><div className="bg-white rounded-xl p-3"><div className="text-[11px] text-slate-500">Processed</div><b className="text-lg">{Math.max(0,Number(data.requests||0)-Number(data.pendingReview||0))}</b></div></div></div><button type="button" disabled={agentBusy} onClick={runAgent} className="mt-4 w-full py-2.5 rounded-xl bg-[#0f766e] text-white text-sm font-semibold disabled:opacity-50">{agentBusy?'Processing request set…':'Process requests with AI agent'}</button></Card>
  </div>
  <div className="grid xl:grid-cols-3 gap-5 mt-5">
   <Card className="xl:col-span-2 p-5"><div className="flex items-center justify-between mb-4"><h2 className="font-bold text-[#0b1f44]">AI allocation insights</h2><Link to="/agent" className="text-xs font-semibold text-blue-600 hover:text-blue-800">Open AI Agent →</Link></div><div className="space-y-3"><Link to="/agent" className="w-full text-left p-4 rounded-xl bg-blue-50/70 border border-blue-100 flex gap-3 hover:bg-blue-100"><div className="w-9 h-9 rounded-lg bg-white text-blue-600 flex items-center justify-center shrink-0"><BrainCircuit size={18}/></div><div className="flex-1"><div className="flex items-center gap-2"><b className="text-sm">Agent-assisted allocation analysis</b><AiPill/></div><p className="text-xs text-slate-600 mt-1">The agent uses the faculty, course, request and workload data stored by the application.</p></div><ArrowUpRight size={16} className="text-blue-500"/></Link><Link to="/conflicts" className="w-full text-left p-4 rounded-xl border border-slate-200 flex gap-3 hover:bg-slate-50"><div className="w-9 h-9 rounded-lg bg-emerald-50 text-emerald-600 flex items-center justify-center"><CheckCircle2 size={18}/></div><div><b className="text-sm">Review constraints and conflicts</b><p className="text-xs text-slate-500 mt-1">Open conflicts before approving recommendations.</p></div></Link></div></Card>
   <Card className="p-5"><div className="flex items-center justify-between mb-4"><h2 className="font-bold text-[#0b1f44]">Review queue</h2><Link to="/review" className="text-xs font-semibold text-blue-600 hover:text-blue-800">View all →</Link></div><div className="space-y-1">{(data.pending||[]).slice(0,4).map(x=><Link to="/review" className="w-full text-left py-3 border-b last:border-0 border-slate-100 flex items-center justify-between" key={x._id}><div><b className="text-sm">{x.courseId}</b><div className="text-xs text-slate-500">Faculty {x.facultyId}</div></div><Badge tone="red">Pending</Badge></Link>)}{!data.pending?.length&&<p className="text-sm text-slate-500 py-5">No allocations waiting for HOD review.</p>}</div></Card>
  </div>
  <Card className="mt-5 p-5"><SectionHeader title="Allocation readiness"/><div className="grid md:grid-cols-4 gap-5"><div><div className="flex justify-between text-xs mb-2"><span>Requests</span><b>{data.requests?Math.round((data.requests-data.pendingReview)/data.requests*100):0}%</b></div><Progress value={data.requests?((data.requests-data.pendingReview)/data.requests*100):0}/></div><div><div className="flex justify-between text-xs mb-2"><span>Faculty loaded</span><b>{data.faculty?100:0}%</b></div><Progress value={data.faculty?100:0}/></div><div><div className="flex justify-between text-xs mb-2"><span>Courses loaded</span><b>{data.courses?100:0}%</b></div><Progress value={data.courses?100:0}/></div><div><div className="flex justify-between text-xs mb-2"><span>HOD decisions</span><b>{data.requests?Math.round((data.requests-data.pendingReview)/data.requests*100):0}%</b></div><Progress value={data.requests?((data.requests-data.pendingReview)/data.requests*100):0}/></div></div></Card>
 </div>
}
