import React,{useEffect,useState} from 'react';
import {BookOpen,CheckCircle2,Clock3,UserRound,Bell,ArrowRight} from 'lucide-react';
import {Link} from 'react-router-dom';
import {Card,PageTitle,Badge,Stat} from '../components/UI';
import {apiRequest} from '../api';

export default function FacultyDashboard(){
 const [items,setItems]=useState([]),[notifications,setNotifications]=useState([]),[error,setError]=useState('');
 const user=(()=>{try{return JSON.parse(sessionStorage.getItem('allocation_user')||'null')}catch{return null}})();
 useEffect(()=>{Promise.all([apiRequest({method:'GET',url:'/allocations/my'}),apiRequest({method:'GET',url:'/allocations/notifications'})]).then(([a,n])=>{setItems(a.data||[]);setNotifications(n.data||[])}).catch(e=>setError(e?.response?.data?.message||'Could not load your dashboard'))},[]);
 const approved=items.filter(item=>item.status==='approved').length;
 const pending=items.filter(item=>item.status==='pending'||item.status==='recommended').length;
 return <div className="w-full max-w-[1600px] mx-auto"><PageTitle eyebrow="FACULTY WORKSPACE" title={`Welcome, ${user?.name||'Faculty'}`} desc="Your personal allocation status and academic profile."/>
  {error&&<div className="mb-4 p-3 rounded-xl alert-error text-sm">{error}</div>}
  <div className="grid grid-cols-2 md:grid-cols-4 gap-4"><Stat label="My requests" value={items.length} sub="Your submitted requests" icon={BookOpen}/><Stat label="Approved" value={approved} sub="HOD-approved subjects" icon={CheckCircle2} tone="blue"/><Stat label="Pending review" value={pending} sub="Awaiting HOD decision" icon={Clock3} tone="amber"/><Stat label="Account" value="Faculty" sub="Personal workspace" icon={UserRound}/></div>
    <Card className="mt-5 p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="font-display font-semibold text-slate-800">My proposed allocations</h2><p className="text-xs text-slate-500 mt-1">Only your own requests and decisions are shown.</p></div><Link to="/my-allocation" className="text-xs font-semibold text-blue-700">View details</Link></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3 mt-5">{items.slice(0,6).map(item=><div key={item._id} className="min-h-28 flex flex-col justify-between gap-3 rounded-xl border border-slate-200 p-4"><div><div className="text-sm font-semibold text-slate-800">{item.courseName||item.courseId}</div><div className="text-xs text-slate-500 mt-1">{item.sectionId||'Section pending'}</div></div><div className="flex items-end justify-between gap-2"><p className="text-xs text-slate-500 line-clamp-2">{item.justification}</p><Badge tone={item.status==='approved'?'green':(item.status==='pending'||item.status==='recommended')?'amber':'red'}>{item.statusLabel||item.status}</Badge></div></div>)}{!items.length&&<div className="md:col-span-2 xl:col-span-3 py-10 text-center text-sm text-slate-500">No allocation requests are linked to this account yet.</div>}</div></Card>
    <Card className="mt-5 p-6"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center"><Bell size={19}/></div><div><h2 className="font-display font-semibold text-slate-800">Notifications</h2><p className="text-xs text-slate-500 mt-1">{notifications.length ? `${notifications.length} allocation update${notifications.length===1?'':'s'}` : 'No new allocation updates yet.'}</p></div></div><Link to="/notifications" className="inline-flex items-center gap-1 text-xs font-semibold text-blue-700">Open center <ArrowRight size={13}/></Link></div>{notifications.slice(0,3).map(n=><div key={n.id} className="mt-4 rounded-xl border border-slate-100 bg-slate-50/70 p-3"><div className="flex items-start gap-3"><div className={`mt-0.5 w-2 h-2 rounded-full ${n.type==='success'?'bg-emerald-500':n.type==='warning'?'bg-amber-500':'bg-blue-500'}`}/><div><p className="text-xs font-semibold text-slate-800">{n.title}</p><p className="text-xs text-slate-500 mt-1">{n.message}</p></div></div></div>)}</Card>
 </div>;
}
