import React,{useState} from 'react';
import axios from 'axios';
import {BrainCircuit,LockKeyhole,ArrowRight,ShieldCheck} from 'lucide-react';
const API=import.meta.env.VITE_API_URL||'http://localhost:5000/api';
export default function Login(){
 const [email,setEmail]=useState('hod@college.edu'); const [password,setPassword]=useState('hod123'); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const login=async()=>{try{setBusy(true);setError('');
   // Demo login is intentionally available for the local CSV deployment and does not need MongoDB.
   const d=await axios.post(`${API}/auth/demo`); sessionStorage.setItem('allocation_demo_token',d.data.token);sessionStorage.setItem('allocation_user',JSON.stringify(d.data.user));window.location.assign('/dashboard');
  }catch(e){setError(e?.response?.data?.message||'Could not sign in. Set DEMO_MODE=true for the local demo.')}finally{setBusy(false)}};
 return <div className="min-h-screen bg-[#f4f8fd] grid place-items-center p-5"><div className="w-full max-w-md"><div className="text-center mb-6"><div className="mx-auto w-14 h-14 rounded-2xl bg-[#0b1f44] text-white grid place-items-center shadow-lg"><BrainCircuit size={28}/></div><h1 className="text-2xl font-black text-[#0b1f44] mt-4">Faculty Course Allocation</h1><p className="text-sm text-slate-500 mt-1">Academic Allocation • 2026–27</p></div><div className="bg-white rounded-3xl border border-slate-200 shadow-xl p-7"><div className="flex items-center gap-2 text-sm font-bold text-[#0b1f44]"><ShieldCheck size={18} className="text-blue-600"/> HOD sign in</div><p className="text-xs text-slate-500 mt-2">Sign in to access the allocation agent, requests and HOD decisions.</p>{error&&<div className="mt-4 p-3 rounded-xl bg-red-50 border border-red-200 text-red-700 text-sm">{error}</div>}<label className="block mt-5 text-xs font-semibold text-slate-600">Email<input value={email} onChange={e=>setEmail(e.target.value)} className="mt-1 w-full px-3 py-3 rounded-xl border border-slate-200"/></label><label className="block mt-3 text-xs font-semibold text-slate-600">Password<div className="relative"><LockKeyhole size={16} className="absolute left-3 top-3.5 text-slate-400"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 w-full pl-9 pr-3 py-3 rounded-xl border border-slate-200"/></div></label><button disabled={busy} onClick={login} className="mt-5 w-full py-3 rounded-xl bg-[#1d4ed8] text-white font-bold flex items-center justify-center gap-2 disabled:opacity-50">{busy?'Signing in…':'Sign in'}<ArrowRight size={17}/></button><div className="mt-4 text-[11px] text-slate-400 text-center">Local demo access uses the configured HOD demo account. API keys stay server-side.</div></div></div></div>;
}
