import React,{useEffect,useState} from 'react';
import {Download,FileSpreadsheet,FileText} from 'lucide-react';
import {Card,PageTitle,Badge} from '../components/UI';
import {apiRequest} from '../api';

function saveFile(name,content,type='text/plain'){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);}
function csv(rows){return rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');}

export default function Reports(){
 const [dashboard,setDashboard]=useState({faculty:0,courses:0,requests:0,pendingReview:0,workload:[]});const [conflicts,setConflicts]=useState([]);const [audit,setAudit]=useState([]);const [msg,setMsg]=useState('');
 const load=async()=>{try{const [d,c,a]=await Promise.all([apiRequest({method:'GET',url:'/allocations/dashboard'}),apiRequest({method:'GET',url:'/data/conflicts'}),apiRequest({method:'GET',url:'/data/audit'})]);setDashboard(d.data||{});setConflicts(c.data||[]);setAudit(a.data||[])}catch(e){setMsg(e?.response?.data?.message||'Could not load report data.')}};
 useEffect(()=>{load()},[]);
 const reportRows=[
  ['Allocation Summary','CSV',`${dashboard.requests||0} requests • ${dashboard.pendingReview||0} pending`],
  ['Faculty Load Statement','CSV',`${dashboard.faculty||0} faculty • live workload capacity`],
  ['Course Coverage Report','CSV',`${dashboard.courses||0} active courses`],
  ['Conflict Analysis','CSV',`${conflicts.filter(x=>x.status!=='resolved').length} active conflicts`],
  ['HOD Decision Audit','CSV',`${audit.length} recorded decisions`]
 ];
 const download=(name)=>{if(name==='Allocation Summary')return saveFile('allocation_summary.csv',csv([['Metric','Value'],['Faculty',dashboard.faculty],['Courses',dashboard.courses],['Requests',dashboard.requests],['Pending Review',dashboard.pendingReview]]),'text/csv');if(name==='Faculty Load Statement')return saveFile('faculty_load.csv',csv([['Faculty','Hours','Max Hours'],...(dashboard.workload||[]).map(x=>[x.name,x.hours,x.max])]),'text/csv');if(name==='Course Coverage Report')return saveFile('course_coverage.csv',`Active courses,${dashboard.courses||0}\n`,'text/csv');if(name==='Conflict Analysis')return saveFile('conflict_analysis.csv',csv([['Conflict','Status','Description'],...conflicts.map(x=>[x.conflictId,x.status,x.description])]),'text/csv');return saveFile('hod_decision_audit.csv',csv([['Action','Entity','Reason','Timestamp'],...audit.map(x=>[x.action,x.entityType,x.reason||'',x.timestamp||x.createdAt||''])]),'text/csv');};
 const exportAll=()=>{reportRows.forEach((r,i)=>setTimeout(()=>download(r[0]),i*150));setMsg('Live reports prepared from current backend data.');setTimeout(()=>setMsg(''),3000)};
 const downloadApproved=async(format)=>{try{const r=await apiRequest({method:'GET',url:`/allocations/export?format=${format}`});const content=format==='json'?JSON.stringify(r.data,null,2):r.data;saveFile(`approved_allocations.${format}`,content,format==='json'?'application/json':'text/csv');setMsg('Export contains HOD-approved allocations only.')}catch(e){setMsg(e?.response?.data?.message||'Could not export approved allocations.')}};
 return <div><PageTitle eyebrow="DOCUMENT CENTER" title="Reports & Audit" desc="Reports are generated from the current backend dataset; no placeholder totals are used." action={<button type="button" onClick={exportAll} className="px-4 py-2.5 rounded-xl btn-primary text-sm flex gap-2 items-center"><Download size={17}/> Export reports</button>}/>{msg&&<div className="mb-4 p-3 rounded-xl alert-success text-sm font-semibold">{msg}</div>}<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{reportRows.map((r,i)=><Card className="p-5" key={r[0]}><div className="flex items-center justify-between"><div className="w-11 h-11 rounded-xl bg-cyan-400/10 text-cyan-700 flex items-center justify-center">{i===1||i===4?<FileSpreadsheet/>:<FileText/>}</div><Badge tone="green">Live</Badge></div><h3 className="font-display font-semibold mt-4 text-slate-800">{r[0]}</h3><p className="text-xs text-slate-500 mt-1">{r[2]}</p><button type="button" onClick={()=>download(r[0])} className="btn-outline mt-5 w-full py-2.5 rounded-xl text-sm flex justify-center items-center gap-2"><Download size={15}/> Download CSV</button></Card>)}</div><Card className="mt-5 p-5"><h2 className="font-display font-semibold text-slate-800">Approved allocation export</h2><p className="text-xs text-slate-500 mt-1">Only allocations explicitly approved by the HOD or Dean are included.</p><div className="flex gap-2 mt-4"><button type="button" onClick={()=>downloadApproved('json')} className="btn-outline px-4 py-2 rounded-lg text-sm flex items-center gap-2"><Download size={15}/> JSON</button><button type="button" onClick={()=>downloadApproved('csv')} className="btn-outline px-4 py-2 rounded-lg text-sm flex items-center gap-2"><Download size={15}/> CSV</button></div></Card><Card className="mt-5 p-5"><h2 className="font-display font-semibold text-slate-800">Audit log</h2><p className="text-xs text-slate-500 mt-1">Recent HOD/Dean decisions, overrides, and stored reasons.</p><div className="mt-4 space-y-2">{audit.map(item=><div className="rounded-lg border border-slate-200 p-3" key={item._id}><div className="flex items-center justify-between gap-2"><b className="text-xs text-slate-700">{item.action}</b><span className="text-[11px] text-slate-400">{item.timestamp||item.createdAt||''}</span></div><div className="text-xs text-slate-500 mt-1">{item.reason||'No reason recorded.'}</div></div>)}{!audit.length&&<div className="text-sm text-slate-500">No audit entries available.</div>}</div></Card></div>}
