import React from 'react';
import {ChevronRight,AlertTriangle,CheckCircle2,Clock3,Sparkles,X} from 'lucide-react';
export const Card=({children,className=''})=><div className={`bg-white border border-slate-200 rounded-2xl shadow-[0_8px_30px_rgba(30,64,175,.05)] ${className}`}>{children}</div>;
export const PageTitle=({eyebrow,title,desc,action})=><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 mb-6"><div><div className="text-[11px] font-bold uppercase tracking-[.16em] text-blue-600 mb-1">{eyebrow}</div><h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-[#0b1f44]">{title}</h1>{desc&&<p className="text-sm text-slate-500 mt-1 max-w-2xl">{desc}</p>}</div>{action}</div>;
export const Badge=({children,tone='blue'})=>{const c={blue:'bg-blue-50 text-blue-700',green:'bg-emerald-50 text-emerald-700',amber:'bg-amber-50 text-amber-700',red:'bg-red-50 text-red-700',slate:'bg-slate-100 text-slate-600'}[tone]||'bg-blue-50 text-blue-700';return <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-semibold ${c}`}>{children}</span>};
export const Stat=({label,value,sub,icon:Icon,tone='blue'})=><Card className="p-5"><div className="flex items-start justify-between"><div><div className="text-xs font-medium text-slate-500">{label}</div><div className="text-2xl font-bold text-[#0b1f44] mt-1">{value}</div><div className="text-xs text-slate-500 mt-1">{sub}</div></div><div className={`w-10 h-10 rounded-xl flex items-center justify-center ${tone==='blue'?'bg-blue-50 text-blue-600':tone==='amber'?'bg-amber-50 text-amber-600':tone==='green'?'bg-emerald-50 text-emerald-600':'bg-red-50 text-red-600'}`}><Icon size={19}/></div></div></Card>;
export const SectionHeader=({title,link,onClick})=><div className="flex items-center justify-between mb-4"><h2 className="font-bold text-[#0b1f44]">{title}</h2>{link&&<button type="button" onClick={onClick} className="text-xs font-semibold text-blue-600 flex items-center gap-1 hover:text-blue-800">{link}<ChevronRight size={14}/></button>}</div>;
export const Progress=({value})=><div className="h-2 rounded-full bg-slate-100 overflow-hidden"><div className="h-full rounded-full bg-blue-600" style={{width:`${Math.min(value,100)}%`}}/></div>;
export const AiPill=()=> <Badge><Sparkles size={12}/> AI analyzed</Badge>;
export function Modal({open,title,onClose,children}){if(!open)return null;return <div className="fixed inset-0 z-[100] bg-slate-950/40 flex items-center justify-center p-4" onMouseDown={e=>{if(e.target===e.currentTarget)onClose?.()}}><div className="w-full max-w-lg bg-white rounded-2xl shadow-2xl overflow-hidden"><div className="px-5 py-4 border-b flex items-center justify-between"><h2 className="font-bold text-[#0b1f44]">{title}</h2><button type="button" onClick={onClose} className="p-2 rounded-lg hover:bg-slate-100"><X size={18}/></button></div><div className="p-5">{children}</div></div></div>}
export const Field=({label,...props})=><label className="block"><span className="block text-xs font-semibold text-slate-600 mb-1.5">{label}</span><input {...props} className={`w-full px-3 py-2.5 rounded-xl border border-slate-200 outline-none focus:ring-2 focus:ring-blue-100 ${props.className||''}`}/></label>;
